### ISSUE TITLE
Disconnect crashed

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#125]
I logged in, then I got a bunch of presence events but the roster was empty. Then I disconnected and it crashed:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x41d1770]

goroutine 31 [running]:
github.com/twstrike/coyim/session.(*Session).WatchRosterEvents(0xc8201be0e0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:635 +0x2e0
created by github.com/twstrike/coyim/session.(*Session).Connect
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:702 +0x375

goroutine 1 [syscall, locked to thread]:
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	??:0 +0x31
github.com/gotk3/gotk3/gtk.Main()
	/Users/rjunior/go/src/github.com/gotk3/gotk3/gtk/gtk.go:840 +0x14
github.com/twstrike/coyim/gui.(*gtkUI).Loop(0xc82000e4e0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:202 +0x9b
main.runClient()
	/Users/rjunior/go/src/github.com/twstrike/coyim/gtk.go:8 +0x35
main.main()
	/Users/rjunior/go/src/github.com/twstrike/coyim/main.go:27 +0x22

goroutine 17 [syscall, 1 minutes, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [select]:
github.com/twstrike/coyim/gui.NewGTK.func1(0xc82000e300, 0xc82000e4e0, 0xc82000e360, 0xc82000e3c0, 0xc82000e420)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:74 +0x403
created by github.com/twstrike/coyim/gui.NewGTK
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:97 +0x530

goroutine 6 [runnable]:
github.com/gotk3/gotk3/glib.IdleAdd(0x4530b00, 0xc82040e2a0, 0x0, 0x0, 0x0, 0x1d69, 0x0, 0x0)
	/Users/rjunior/go/src/github.com/gotk3/gotk3/glib/glib.go:331
github.com/twstrike/coyim/gui.(*gtkUI).observeAccountEvents(0xc82000e4e0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account_events.go:20 +0x54e
created by github.com/twstrike/coyim/gui.(*gtkUI).Loop
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:198 +0x60

goroutine 18 [chan receive, 1 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).listenToToggleConnectAllAutomatically(0xc82000e4e0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:401 +0x3a
created by github.com/twstrike/coyim/gui.(*gtkUI).configLoaded
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:162 +0x1bc

goroutine 8 [chan receive, 1 minutes]:
github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu.func5(0xc82000e840, 0xc820030270, 0xc820030280, 0xc820188270)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:112 +0x5d
created by github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:134 +0x67e

goroutine 9 [chan receive]:
github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu.func5(0xc82000e8a0, 0xc8200302d0, 0xc8200302e0, 0xc820188360)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:112 +0x5d
created by github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:134 +0x67e

goroutine 33 [runnable]:
net.runtime_pollWait(0x71b5e20, 0x72, 0xc820014130)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82005c300, 0x72, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82005c300, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82005c2a0, 0xc820201000, 0x1000, 0x1000, 0x0, 0x71b0028, 0xc820014130)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820186188, 0xc820201000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc820188780, 0xe6fc138, 0xc820186188, 0x5, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8201fe000, 0x49be417, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8201fe000, 0xc820207000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/crypto/tls/conn.go:901 +0x167
bufio.(*Reader).fill(0xc8201d9380)
	/usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadByte(0xc8201d9380, 0xc820467f80, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/bufio/bufio.go:229 +0x7a
encoding/xml.(*Decoder).getc(0xc8201b1080, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/encoding/xml/xml.go:861 +0xad
encoding/xml.(*Decoder).rawToken(0xc8201b1080, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/encoding/xml/xml.go:512 +0x148
encoding/xml.(*Decoder).Token(0xc8201b1080, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/encoding/xml/xml.go:247 +0xe83
github.com/twstrike/coyim/xmpp.nextStart(0xc8201b1080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/xml.go:40 +0x7c
github.com/twstrike/coyim/xmpp.next(0xc8201682a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/xml.go:56 +0x7d
github.com/twstrike/coyim/xmpp.(*Conn).Next(0xc8201682a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/connection.go:54 +0xab
github.com/twstrike/coyim/session.(*Session).readMessages(0xc8201be0e0, 0xc8201d9aa0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:111 +0x61
created by github.com/twstrike/coyim/session.(*Session).WatchStanzas
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:247 +0x88

goroutine 30 [chan receive]:
github.com/twstrike/coyim/session.(*Session).WatchTimeout(0xc8201be0e0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:582 +0x104
created by github.com/twstrike/coyim/session.(*Session).Connect
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:701 +0x350

goroutine 32 [chan receive]:
github.com/twstrike/coyim/session.(*Session).receiveStanza(0xc8201be0e0, 0xc8201d9aa0, 0xc8201be001)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:221 +0x89
github.com/twstrike/coyim/session.(*Session).WatchStanzas(0xc8201be0e0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:248 +0xa0
created by github.com/twstrike/coyim/session.(*Session).Connect
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:703 +0x39a

goroutine 50 [sleep]:
time.Sleep(0x2540be400)
	/usr/local/Cellar/go/1.5.1/libexec/src/runtime/time.go:59 +0xf9
github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu.func5.1(0xc820188360)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:121 +0x26
created by github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu.func5
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:124 +0x168

goroutine 144 [runnable]:
github.com/twstrike/coyim/session.publishEvent.func1(0x47c0380, 0xc8204300b0, 0xc82000e8a0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:95
created by github.com/twstrike/coyim/session.publishEvent
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:97 +0x49

goroutine 142 [runnable]:
github.com/twstrike/coyim/session.publishEvent.func1(0x47c0380, 0xc8204300a0, 0xc82000e8a0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:95
created by github.com/twstrike/coyim/session.publishEvent
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:97 +0x49

goroutine 156 [runnable]:
github.com/twstrike/coyim/session.publishEvent.func1(0x47c0380, 0xc820438ac0, 0xc82000e480)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:95
created by github.com/twstrike/coyim/session.publishEvent
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:97 +0x49

goroutine 143 [runnable]:
github.com/twstrike/coyim/session.publishEvent.func1(0x47c0380, 0xc8204300b0, 0xc82000e480)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:95
created by github.com/twstrike/coyim/session.publishEvent
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:97 +0x49

goroutine 157 [runnable]:
github.com/twstrike/coyim/session.publishEvent.func1(0x47c0380, 0xc820438ac0, 0xc82000e8a0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:95
created by github.com/twstrike/coyim/session.publishEvent
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:97 +0x49

goroutine 158 [runnable]:
github.com/twstrike/coyim/session.publishEvent.func1(0x47c0380, 0xc820438ad0, 0xc82000e480)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:95
created by github.com/twstrike/coyim/session.publishEvent
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:97 +0x49

goroutine 159 [runnable]:
github.com/twstrike/coyim/session.publishEvent.func1(0x47c0380, 0xc820438ad0, 0xc82000e8a0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:95
created by github.com/twstrike/coyim/session.publishEvent
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:97 +0x49
```

**Comment by juniorz** [comment]
Oh! And I never got the `>>> INFO Roster received` message.

**Comment by juniorz** [comment]
It may not be related, but the presence events happened while the roster was loading.

**Comment by olabini** [comment]
Hm. The roster stuff should be loaded lazily, and merge the data. It's surprising if that causes a crash. =/

**Comment by olabini** [comment]
Your crash seems to happen in WatchRosterEvents - the only thing that happens before the log statement is s.Conn.SignalPresence("") - so my guess is that the sessions connection wasn't assigned when this was called. But that's just a guess.

**Comment by juniorz** [comment]
I'm still confused by this stacktrace.

On 11/13/15 5:11 PM, Ola Bini wrote:
> Your crash seems to happen in WatchRosterEvents - the only thing that
> happens before the log statement is s.Conn.SignalPresence("") - so my
> guess is that the sessions connection wasn't assigned when this was
> called. But that's just a guess.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/twstrike/coyim/issues/125#issuecomment-156529941>.
> 

-- 
*Reinaldo de Souza Jr* | Software Developer
*Thought*Works Brasil

EF84 6530 67A5 1559 5554 D8B2 954A 6BEF AF74 ACD7

**Comment by olabini** [comment]
Well, the file has changed a bit since you took it, so the numbers are wrong.

**Comment by juniorz** [comment]
We believe to have fixed one issue, and found another. This is the output from `gdb`:

```
(CoyIM:8660): GLib-GObject-CRITICAL **: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
[New Thread 0x210b of process 8660]
[New Thread 0x2203 of process 8660]
[New Thread 0x2303 of process 8660]
[New Thread 0x2403 of process 8660]
[New Thread 0x2503 of process 8660]
[New Thread 0x2603 of process 8660]

Program received signal SIGSEGV, Segmentation fault.
0x0000000005b0368d in gtk_css_style_get_value () from /usr/local/opt/gtk+3/lib/libgtk-3.0.dylib
```

I suspect of `wrapObject` in `gotk3` because it's the place where we sink the reference count.

**Comment by olabini** [comment]
=(

**Comment by juniorz** [comment]
I suspect this is #154. We'll investigate on the other issue.
