### ISSUE TITLE
Verify fingerprint crashes with config file having `PrivateKey` property

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#162]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x38 pc=0x407d122]

goroutine 1 [running]:
github.com/twstrike/coyim/gui.verifyFingerprintDialog(0xc8200108a0, 0xc820447100, 0x11, 0xc8200ec3f0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/fingerprint_verification.go:38 +0xbb2
github.com/twstrike/coyim/gui.newConversationWindow.func4()
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/conversation.go:142 +0x40
reflect.Value.call(0x4554d80, 0xc820137740, 0x13, 0x488a670, 0x4, 0x4e4dbf0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.5.1/libexec/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x4554d80, 0xc820137740, 0x13, 0x4e4dbf0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.1/libexec/src/reflect/value.go:300 +0xb1
github.com/gotk3/gotk3/glib.goMarshal(0x11731150, 0x0, 0x7fff00000001, 0x7fff5fbfeec0, 0x7fff5fbfee50, 0x0)
	/Users/rjunior/go/src/github.com/gotk3/gotk3/glib/glib.go:299 +0xa33
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	??:0 +0x31
github.com/gotk3/gotk3/gtk.Main()
	/Users/rjunior/go/src/github.com/gotk3/gotk3/gtk/gtk.go:846 +0x14
github.com/twstrike/coyim/gui.(*gtkUI).Loop(0xc8200ba420)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:213 +0xaa
main.runClient()
	/Users/rjunior/go/src/github.com/twstrike/coyim/gtk.go:8 +0x35
main.main()
	/Users/rjunior/go/src/github.com/twstrike/coyim/main.go:27 +0x22
```

**Comment by juniorz** [comment]
Fixed by 9bdbf26b7ea877398173d305e56e85c4d56c93c3. See comments in 9e07357e for more information.
