### ISSUE TITLE
CoyIM crashes when is connecting

### ISSUE THREAD

**Issue by tdruiva** [twstrike/coyim#173]
When accounts in CoyIM is setup to `Connect On Startup` and you try to connect manually, this crashes CoyIM.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4ad6ae]

goroutine 1 [running]:
github.com/twstrike/coyim/gui.(*account).removeConnectionNotification(0xc82019a8e0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/account.go:162 +0x5e
github.com/twstrike/coyim/gui.(*gtkUI).removeConnectAccountNotification.func1()
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/notifications.go:23 +0x20
reflect.Value.call(0x9a6420, 0xc8203044b0, 0x13, 0xcfae30, 0x4, 0x153b428, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x9a6420, 0xc8203044b0, 0x13, 0x153b428, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/reflect/value.go:300 +0xb1
github.com/gotk3/gotk3/glib.sourceAttach.func1()
	/home/tsilva/gopackages/src/github.com/gotk3/gotk3/glib/glib.go:310 +0x1d4
reflect.Value.call(0x9a6420, 0xc820300190, 0x13, 0xcfae30, 0x4, 0x153b428, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/golang/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0x9a6420, 0xc820300190, 0x13, 0x153b428, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/reflect/value.go:300 +0xb1
github.com/gotk3/gotk3/glib.goMarshal(0x7f4204001150, 0x7ffea9f1c5a0, 0x7f4200000000, 0x0, 0x0, 0x0)
	/home/tsilva/gopackages/src/github.com/gotk3/gotk3/glib/glib.go:215 +0xa33
github.com/gotk3/gotk3/gtk._Cfunc_gtk_main()
	??:0 +0x31
github.com/gotk3/gotk3/gtk.Main()
	/home/tsilva/gopackages/src/github.com/gotk3/gotk3/gtk/gtk.go:846 +0x14
github.com/twstrike/coyim/gui.(*gtkUI).Loop(0xc82001caf0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/ui.go:209 +0xaa
main.runClient()
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gtk.go:8 +0x35
main.main()
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/main.go:27 +0x22

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [chan receive]:
github.com/twstrike/coyim/gui.(*gtkUI).watchCommands(0xc82001caf0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/commands.go:19 +0x91
created by github.com/twstrike/coyim/gui.(*gtkUI).Loop
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/ui.go:204 +0x39

goroutine 6 [chan receive]:
github.com/twstrike/coyim/gui.(*gtkUI).observeAccountEvents(0xc82001caf0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/account_events.go:14 +0xa9
created by github.com/twstrike/coyim/gui.(*gtkUI).Loop
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/ui.go:205 +0x5b

goroutine 40 [chan receive]:
github.com/twstrike/coyim/xmpp.(*Conn).watchPings(0xc8200c4240)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/xmpp/ping.go:66 +0x1d6
created by github.com/twstrike/coyim/xmpp.(*Dialer).setupStream
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/xmpp/dialer.go:126 +0xa01

goroutine 51 [chan receive]:
github.com/twstrike/coyim/gui.(*gtkUI).listenToToggleConnectAllAutomatically(0xc82001caf0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/ui.go:438 +0x3a
created by github.com/twstrike/coyim/gui.(*gtkUI).configLoaded
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/ui.go:151 +0x26b

goroutine 20 [chan receive]:
github.com/twstrike/coyim/gui.(*account).watchAndToggleMenuItems(0xc82019a740, 0xc820034068, 0xc820034078)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/account.go:113 +0xb5
created by github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/account.go:105 +0x772

goroutine 21 [runnable]:
github.com/twstrike/coyim/gui.(*account).watchAndToggleMenuItems(0xc82019a8e0, 0xc820034168, 0xc820034190)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/account.go:113 +0xb5
created by github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/account.go:105 +0x772

goroutine 22 [chan receive]:
github.com/twstrike/coyim/gui.(*account).watchAndToggleMenuItems(0xc82019aa80, 0xc820034240, 0xc820034250)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/account.go:113 +0xb5
created by github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/gui/account.go:105 +0x772

goroutine 46 [IO wait]:
net.runtime_pollWait(0x7f422805bd58, 0x72, 0xc82000a180)
	/usr/lib/golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82001c220, 0x72, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82001c220, 0x0, 0x0)
	/usr/lib/golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82001c1c0, 0xc8200e0c00, 0x400, 0x400, 0x0, 0x7f422c696028, 0xc82000a180)
	/usr/lib/golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8201cc058, 0xc8200e0c00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8200fa120, 0x7f422805be68, 0xc8201cc058, 0x5, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8200c2580, 0xe87c17, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc8200c2580, 0xc820021000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/crypto/tls/conn.go:901 +0x167
bufio.(*Reader).fill(0xc8201dd8c0)
	/usr/lib/golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadByte(0xc8201dd8c0, 0x725fda, 0x0, 0x0)
	/usr/lib/golang/src/bufio/bufio.go:229 +0x7a
encoding/xml.(*Decoder).getc(0xc8201b0dc0, 0xc82001c254)
	/usr/lib/golang/src/encoding/xml/xml.go:861 +0xad
encoding/xml.(*Decoder).rawToken(0xc8201b0dc0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/encoding/xml/xml.go:512 +0x148
encoding/xml.(*Decoder).Token(0xc8201b0dc0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/encoding/xml/xml.go:247 +0xe83
github.com/twstrike/coyim/xmpp.nextElement(0xc8201b0dc0, 0x0, 0x0, 0x0, 0x0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/xmpp/xml.go:42 +0x7b
github.com/twstrike/coyim/xmpp.next(0xc8200c4240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/xmpp/xml.go:79 +0xac
github.com/twstrike/coyim/xmpp.(*Conn).Next(0xc8200c4240, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/xmpp/connection.go:123 +0xab
github.com/twstrike/coyim/xmpp.(*Conn).ReadStanzas(0xc8200c4240, 0xc82021a5a0, 0x0, 0x0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/xmpp/connection.go:212 +0x9e
github.com/twstrike/coyim/session.(*Session).readStanzasAndAlertOnErrors(0xc8200d2500, 0xc82021a5a0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/session.go:274 +0x40
created by github.com/twstrike/coyim/session.(*Session).watchStanzas
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/session.go:268 +0x88

goroutine 54 [chan receive]:
github.com/twstrike/coyim/xmpp.(*Conn).watchKeepAlive(0xc8200c4240, 0x7f422805ad88, 0xc8201cc058)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/xmpp/keepalive.go:24 +0x1b2
created by github.com/twstrike/coyim/xmpp.(*Dialer).setupStream
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/xmpp/dialer.go:100 +0x2cf

goroutine 41 [runnable]:
github.com/twstrike/coyim/session.(*Session).publishEventTo(0xc8200d2500, 0xc8200224e0, 0xc70c60, 0xc8203044a0)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/events.go:111
created by github.com/twstrike/coyim/session.(*Session).publishEvent
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/events.go:142 +0x107

goroutine 43 [runnable]:
github.com/twstrike/coyim/session.(*Session).requestRoster(0xc8200d2500)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/session.go:650
created by github.com/twstrike/coyim/session.(*Session).Connect
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/session.go:734 +0x3ce

goroutine 44 [runnable]:
github.com/twstrike/coyim/session.(*Session).watchTimeout(0xc8200d2500)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/session.go:612
created by github.com/twstrike/coyim/session.(*Session).Connect
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/session.go:735 +0x3f3

goroutine 45 [chan receive]:
github.com/twstrike/coyim/session.(*Session).receiveStanza(0xc8200d2500, 0xc82021a5a0, 0xc8200d2500)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/session.go:242 +0x89
github.com/twstrike/coyim/session.(*Session).watchStanzas(0xc8200d2500)
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/session.go:269 +0xa0
created by github.com/twstrike/coyim/session.(*Session).Connect
	/home/tsilva/gopackages/src/github.com/twstrike/coyim/session/session.go:736 +0x418
```

**Comment by olabini** [comment]
Can you verify whether this still happens? I think it's been fixed.

**Comment by tdruiva** [comment]
@olabini still happening, today I saw an error:
```
>>> ALERT error reading XMPP message: read tcp 127.0.0.1:48244->127.0.0.1:9050: use of closed network connection
```
And CoyIM frozen...

**Comment by olabini** [comment]
=( Hmm.....

**Comment by olabini** [comment]
Is this still happening? I've never seen these things.

**Comment by olabini** [comment]
Ping

**Comment by myfreeweb** [comment]
I get a different crash when connecting:
```
panic: gui: failed load Conversation: Invalid property: GtkTextView.top-margin on line 122
```

After removing the top-margin, it says the same about bottom-margin. After removing bottom-margin, everything works.

```diff
diff --git i/gui/definitions/Conversation.xml w/gui/definitions/Conversation.xml
index 7eb1cc2..9a49dff 100644
--- i/gui/definitions/Conversation.xml
+++ w/gui/definitions/Conversation.xml
@@ -119,8 +119,6 @@
                 <property name="pixels-below-lines">5</property>
                 <property name="left-margin">5</property>
                 <property name="right-margin">5</property>
-                <property name="top-margin">5</property>
-                <property name="bottom-margin">5</property>
               </object>
             </child>
           </object>
diff --git i/gui/definitions/conversation.go w/gui/definitions/conversation.go
index 3d51351..eb2a90d 100644
--- i/gui/definitions/conversation.go
+++ w/gui/definitions/conversation.go
@@ -129,8 +129,6 @@ func (*defConversation) String() string {
                 <property name="pixels-below-lines">5</property>
                 <property name="left-margin">5</property>
                 <property name="right-margin">5</property>
-                <property name="top-margin">5</property>
-                <property name="bottom-margin">5</property>
               </object>
             </child>
           </object>
```

FreeBSD 11-CURRENT, GTK 3.16.7

**Comment by olabini** [comment]
Ah, thanks - good catch. top-margin and bottom-margin were added in GTK 3.18 - I've just pushed a fix to this.

**Comment by olabini** [comment]
Since this hasn't happened again, we'll close it.
