### ISSUE TITLE
Nil pointer dereference

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#219]
When I run the app built from d445462 there is a nil pointer dereference:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x48 pc=0x407641c]

goroutine 18 [running]:
runtime.gopanic(0x47a5020, 0xc820014110)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/panic.go:461 +0x3e6 fp=0xc82004de48 sp=0xc82004ddc8
runtime.panicmem()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/panic.go:42 +0x49 fp=0xc82004de70 sp=0xc82004de48
runtime.sigpanic()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/sigpanic_unix.go:24 +0x2c9 fp=0xc82004dec0 sp=0xc82004de70
github.com/twstrike/coyim/gui.(*roster).update(0x0, 0xc82017ca80, 0xc82016a0f8)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/roster.go:253 +0x1c fp=0xc82004dee0 sp=0xc82004dec0
github.com/twstrike/coyim/gui.(*gtkUI).addInitialAccountsToRoster(0xc82005ca80)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:292 +0xf5 fp=0xc82004df58 sp=0xc82004dee0
github.com/twstrike/coyim/gui.(*gtkUI).configLoaded(0xc82005ca80, 0xc820174000)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:151 +0xa0 fp=0xc82004df80 sp=0xc82004df58
github.com/twstrike/coyim/gui.(*gtkUI).loadConfig.func1(0xc820174000)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:114 +0x2a fp=0xc82004df98 sp=0xc82004df80
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc82004dfa0 sp=0xc82004df98
created by github.com/twstrike/coyim/config.(*ApplicationConfig).accountLoaded
	/Users/rjunior/go/src/github.com/twstrike/coyim/config/application_config.go:47 +0x11b
```

It happens right after starting the app.

**Comment by brl** [comment]
The root of this problem is that if you are not using an encrypted configuration the roster is populated before u.mainWindow() has run.

I fixed this in my branch yesterday, but I'm unsure if what I did was the ideal way to repair it.

I found the commit which introduced it with git bisect: f8b5bd83036b8a7e5d44725996fb91cf3fe51f8f

**Comment by olabini** [comment]
I think the fix is fine - I've pushed it.
