### ISSUE TITLE
Removing an account while it is attempting to connect crashes CoyIM

### ISSUE THREAD

**Issue by xSmurf** [twstrike/coyim#262]
Built with revision d27b6dc7

```
*** Error in `/usr/bin-oz/coyim': double free or corruption (out): 0x0000000004f8a640 ***
SIGABRT: abort
PC=0x3bf1c7c7507 m=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x9e3730, 0xc820161090, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:120 +0x11b fp=0xc820161048 sp=0xc820161018
github.com/gotk3/gotk3/gtk._Cfunc_gtk_widget_set_sensitive(0x500b2f0, 0x1)
	??:0 +0x35 fp=0xc820161090 sp=0xc820161048
github.com/gotk3/gotk3/gtk.(*Widget).SetSensitive(0xc82002e1d8, 0xc820161001)
	/home/user/Documents/Code/coyim/src/github.com/gotk3/gotk3/gtk/widget.go:314 +0x42 fp=0xc8201610a8 sp=0xc820161090
github.com/twstrike/coyim/gui.toggleConnectAndDisconnectMenuItems.func1()
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/accounts_menu.go:20 +0x6c fp=0xc8201610e0 sp=0xc8201610a8
github.com/twstrike/coyim/gui.doInUIThread.func1()
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/ui_thread.go:19 +0x4a fp=0xc820161100 sp=0xc8201610e0
runtime.call32(0xc820019630, 0xc82056e000, 0x16f8248, 0x0)
	/usr/lib/go/src/runtime/asm_amd64.s:437 +0x3e fp=0xc820161128 sp=0xc820161100
reflect.Value.call(0xa36980, 0xc82056e000, 0x13, 0xdf8628, 0x4, 0x16f8248, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/reflect/value.go:432 +0x120a fp=0xc820161478 sp=0xc820161128
reflect.Value.Call(0xa36980, 0xc82056e000, 0x13, 0x16f8248, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/reflect/value.go:300 +0xb1 fp=0xc8201614d8 sp=0xc820161478
github.com/gotk3/gotk3/glib.sourceAttach.func1()
	/home/user/Documents/Code/coyim/src/github.com/gotk3/gotk3/glib/glib.go:310 +0x1d4 fp=0xc8201615d8 sp=0xc8201614d8
runtime.call32(0xc820019630, 0xc82039e000, 0x16f8248, 0x0)
	/usr/lib/go/src/runtime/asm_amd64.s:437 +0x3e fp=0xc820161600 sp=0xc8201615d8
reflect.Value.call(0xa36980, 0xc82039e000, 0x13, 0xdf8628, 0x4, 0x16f8248, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/reflect/value.go:432 +0x120a fp=0xc820161950 sp=0xc820161600
reflect.Value.Call(0xa36980, 0xc82039e000, 0x13, 0x16f8248, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/reflect/value.go:300 +0xb1 fp=0xc8201619b0 sp=0xc820161950
github.com/gotk3/gotk3/glib.goMarshal(0x3bf10008a10, 0x3f4f266de50, 0x3bf00000000, 0x0, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/gotk3/gotk3/glib/glib.go:215 +0xa33 fp=0xc820161bf0 sp=0xc8201619b0
runtime.call64(0x0, 0x3f4f266dce8, 0x3f4f266dd70, 0x30)
	/usr/lib/go/src/runtime/asm_amd64.s:438 +0x3e fp=0xc820161c38 sp=0xc820161bf0
runtime.cgocallbackg1()
	/usr/lib/go/src/runtime/cgocall.go:252 +0x10c fp=0xc820161c70 sp=0xc820161c38
runtime.cgocallbackg()
	/usr/lib/go/src/runtime/cgocall.go:177 +0xd7 fp=0xc820161cd0 sp=0xc820161c70
runtime.cgocallback_gofunc(0x449413, 0x9e44f0, 0xc820161d60)
	/usr/lib/go/src/runtime/asm_amd64.s:826 +0x60 fp=0xc820161ce0 sp=0xc820161cd0
runtime.asmcgocall(0x9e44f0, 0xc820161d60)
	/usr/lib/go/src/runtime/asm_amd64.s:677 +0x42 fp=0xc820161ce8 sp=0xc820161ce0
runtime.cgocall(0x9e44f0, 0xc820161d60, 0x0)
	/usr/lib/go/src/runtime/cgocall.go:121 +0x133 fp=0xc820161d18 sp=0xc820161ce8
github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x4dd1250, 0x0, 0x4da8f70, 0x0)
	??:0 +0x39 fp=0xc820161d60 sp=0xc820161d18
github.com/gotk3/gotk3/glib.(*Application).Run(0xc82002e088, 0xc820161e48, 0x0, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/gotk3/gotk3/glib/application.go:199 +0x1c2 fp=0xc820161df0 sp=0xc820161d60
github.com/twstrike/coyim/gui.(*gtkUI).Loop(0xc820078990)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/ui.go:255 +0x103 fp=0xc820161e80 sp=0xc820161df0
main.runClient()
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gtk.go:12 +0x65 fp=0xc820161ec8 sp=0xc820161e80
main.main()
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/main.go:28 +0x22 fp=0xc820161f40 sp=0xc820161ec8
runtime.main()
	/usr/lib/go/src/runtime/proc.go:111 +0x2b0 fp=0xc820161f90 sp=0xc820161f40
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820161f98 sp=0xc820161f90

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1721 +0x1

goroutine 5 [chan receive]:
github.com/twstrike/coyim/gui.(*gtkUI).watchCommands(0xc820078990)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/commands.go:51 +0x88
created by github.com/twstrike/coyim/gui.(*gtkUI).Loop.func1
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/ui.go:247 +0x3d

goroutine 6 [chan receive]:
github.com/twstrike/coyim/gui.(*gtkUI).observeAccountEvents(0xc820078990)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/account_events.go:45 +0x59
created by github.com/twstrike/coyim/gui.(*gtkUI).Loop.func1
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/ui.go:248 +0x5f

goroutine 19 [chan receive, 3 minutes]:
github.com/twstrike/coyim/session.observe(0xc820280240)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/session/session_observer.go:9 +0xa6
created by github.com/twstrike/coyim/session.Factory
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/session/session.go:122 +0x4cb

goroutine 20 [chan receive]:
github.com/twstrike/coyim/session.checkReconnect(0xc820280240)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/session/reconnect.go:10 +0x5d
created by github.com/twstrike/coyim/session.Factory
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/session/session.go:123 +0x4ed

goroutine 29 [chan receive]:
github.com/twstrike/coyim/session.checkReconnect(0xc820402120)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/session/reconnect.go:10 +0x5d
created by github.com/twstrike/coyim/session.Factory
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/session/session.go:123 +0x4ed

goroutine 21 [chan receive, 3 minutes]:
github.com/twstrike/coyim/gui.(*account).watchAndToggleMenuItems(0xc820278280, 0xc820274438, 0xc820274448)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/account.go:235 +0xe7
created by github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/account.go:227 +0x985

goroutine 28 [chan receive]:
github.com/twstrike/coyim/session.observe(0xc820402120)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/session/session_observer.go:9 +0xa6
created by github.com/twstrike/coyim/session.Factory
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/session/session.go:122 +0x4cb

goroutine 80 [runnable, locked to thread]:
github.com/gotk3/gotk3/gtk._Cfunc_gtk_menu_item_set_submenu(0x4fd8450, 0x553ee70)
	??:0 +0x31
github.com/gotk3/gotk3/gtk.(*MenuItem).SetSubmenu(0xc82002e130, 0x3bf1f0d8188, 0xc82002e1f0)
	/home/user/Documents/Code/coyim/src/github.com/gotk3/gotk3/gtk/gtk.go:5210 +0x57
github.com/twstrike/coyim/gui.(*gtkUI).buildAccountsMenu(0xc820078990)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/accounts_menu.go:77 +0x1cf
github.com/twstrike/coyim/gui.(*gtkUI).initMenuBar.func1()
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/ui.go:499 +0x25
reflect.Value.call(0xa36980, 0xc82000fe10, 0x13, 0xdf8628, 0x4, 0x16f8248, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/lib/go/src/reflect/value.go:432 +0x120a
reflect.Value.Call(0xa36980, 0xc82000fe10, 0x13, 0x16f8248, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/reflect/value.go:300 +0xb1
github.com/gotk3/gotk3/glib.goMarshal(0x50439a0, 0x3bef8001460, 0xc800000002, 0x3bef8001420, 0x3bf0ffd7a70, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/gotk3/gotk3/glib/glib.go:215 +0xa33
github.com/gotk3/gotk3/glib._Cfunc_g_signal_emitv(0x3bef8001420, 0x1, 0x3bef8001460)
	??:0 +0x35
github.com/gotk3/gotk3/glib.(*Object).Emit(0xc82002e0a8, 0xe93f50, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/gotk3/gotk3/glib/glib.go:724 +0x728
github.com/twstrike/coyim/gui.(*gtkUI).saveConfigInternal(0xc820078990, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/ui.go:199 +0xf4
github.com/twstrike/coyim/gui.(*gtkUI).SaveConfig.func1(0xc820078990)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/ui.go:211 +0x30
created by github.com/twstrike/coyim/gui.(*gtkUI).SaveConfig
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/ui.go:215 +0x35

goroutine 31 [chan receive]:
github.com/twstrike/coyim/gui.(*account).watchAndToggleMenuItems(0xc8201a0140, 0xc82002e1d8, 0xc82002e208)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/account.go:235 +0xe7
created by github.com/twstrike/coyim/gui.(*account).buildAccountSubmenu
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/account.go:227 +0x985

goroutine 121 [IO wait]:
net.runtime_pollWait(0x3bf1f0dd6c0, 0x72, 0xc82000e150)
	/usr/lib/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8204b9cd0, 0x72, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8204b9cd0, 0x0, 0x0)
	/usr/lib/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8204b9c70, 0xc820332000, 0x1000, 0x1000, 0x0, 0x3bf1f0d3028, 0xc82000e150)
	/usr/lib/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8202740e8, 0xc820332000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8202c6300, 0x3bf1f0dd840, 0xc8202740e8, 0x5, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc8202ecdc0, 0x14, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*clientHandshakeState).readFinished(0xc8202d13b8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/handshake_client.go:559 +0x55
crypto/tls.(*Conn).clientHandshake(0xc8202ecdc0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/handshake_client.go:218 +0x17da
crypto/tls.(*Conn).Handshake(0xc8202ecdc0, 0x0, 0x0)
	/usr/lib/go/src/crypto/tls/conn.go:974 +0xec
github.com/twstrike/coyim/xmpp.(*dialer).startTLS(0xc8204b51e0, 0x3bf1f0dd868, 0xc820227680, 0x3bf1f0dc7b0, 0xc8202740e8, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/xmpp/tls.go:122 +0x593
github.com/twstrike/coyim/xmpp.(*dialer).negotiateSTARTTLS(0xc8204b51e0, 0x3bf1f0dd868, 0xc820227680, 0x3bf1f0dc7b0, 0xc8202740e8, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/xmpp/tls.go:90 +0x275
github.com/twstrike/coyim/xmpp.(*dialer).negotiateStreamFeatures(0xc8204b51e0, 0x3bf1f0dd868, 0xc820227680, 0x3bf1f0dc7b0, 0xc8202740e8, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/xmpp/dialer.go:146 +0xb1
github.com/twstrike/coyim/xmpp.(*dialer).setupStream(0xc8204b51e0, 0x3bf1f0dc7b0, 0xc8202740e8, 0x0, 0x0, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/xmpp/dialer.go:129 +0x2a5
github.com/twstrike/coyim/xmpp.(*dialer).Dial(0xc8204b51e0, 0x0, 0x0, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/xmpp/dialer.go:115 +0xa4
github.com/twstrike/coyim/config.(*ConnectionPolicy).Connect(0xc8202d1eb0, 0xc820122060, 0x28, 0xc8202e3320, 0x0, 0x0, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/config/connection_policy.go:199 +0xd4
github.com/twstrike/coyim/session.(*session).Connect(0xc820402120, 0xc820122060, 0x28, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/session/session.go:805 +0x2b7
github.com/twstrike/coyim/gui.(*gtkUI).connectWithPassword(0xc820078990, 0xc8201a0140, 0xc820122060, 0x28, 0x0, 0x0)
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/connection.go:29 +0xf4
created by github.com/twstrike/coyim/gui.(*gtkUI).connectAccount
	/home/user/Documents/Code/coyim/src/github.com/twstrike/coyim/gui/connection.go:17 +0xbe

rax    0x0
rbx    0x5a
rcx    0x3bf1c7c7507
rdx    0x6
rdi    0x61bd
rsi    0x61bd
rbp    0x3f4f266d710
rsp    0x3f4f266d378
r8     0x3034366138663430
r9     0x0
r10    0x8
r11    0x206
r12    0x3f4f266d528
r13    0x5a
r14    0x3f4f266d528
r15    0x1
rip    0x3bf1c7c7507
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
```

**Comment by iapazmino** [comment]
It seems any action while trying to connect crashes CoyIM. This is related to #261

**Comment by olabini** [comment]
This looks quite strange though. I can see two calls that are active, the one in toggleConnectAndDisconnectMenuItems, and the one in buildAccountsMenu. Those two should not be possible to have in the same stack trace - they are both always called from the UI thread in the current code base. Because we get the specific error we get, it looks like one of the two MenuItem's are nil when they shouldn't be. But once again I can't see how that could happen. Very strange.

**Comment by olabini** [comment]
Have you seen this again since?

**Comment by olabini** [comment]
I haven't been able to reproduce or figure it out.

**Comment by olabini** [comment]
OK, I tried this several times and removing an account while connecting doesn't seem to crash anything anymore.
