### ISSUE TITLE
clicking on "secure chat" causes crash

### ISSUE THREAD

**Issue by ioerror** [twstrike/coyim#310]
I've been using some incredibly bad wifi in Vietnam. Often, on my sgos machine, I've found that coyim has lost a connection to The One True Jabber Server. While reconnecting, I noticed that someone had tried to contact me - I clicked on the "secure chat" button at the top of the chat window (single pane version). It causes coy to pop with this in the oz logs:
```
Mar 30 18:10:08 subgraph oz-daemon[31646]: 2016/03/30 18:10:08 [coyim] (stderr) 2016/03/30 18:10:08 Starting TLS handshake
Mar 30 18:10:12 subgraph oz-daemon[31646]: 2016/03/30 18:10:12 [torbrowser-launcher] (xpra-server) 2016-03-30 18:10:12,845 removing invalid None property for workspace
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) panic: runtime error: invalid memory address or nil pointer dereference
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) [signal 0xb code=0x1 addr=0xa8 pc=0x596d8e]
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) goroutine 1 [running, locked to thread]:
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) panic(0xe9ff60, 0xc82000e0d0)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/usr/lib/go/src/runtime/panic.go:464 +0x3e6
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) github.com/twstrike/coyim/session.(*session).Send(0xc8201a6000, 0xc820434480, 0x18, 0xc82048ea50, 0xee, 0x0, 0x0)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/home/user/go/src/github.com/twstrike/coyim/session/session.go:141 +0x1ee
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) github.com/twstrike/coyim/client.(*conversation).StartEncryptedChat(0xc820434a20, 0x38a1e77a108, 0xc8201a6000, 0x0, 0x0)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/home/user/go/src/github.com/twstrike/coyim/client/conversation.go:35 +0x40f
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) github.com/twstrike/coyim/gui.(*conversationPane).onStartOtrSignal(0xc82045c000)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/home/user/go/src/github.com/twstrike/coyim/gui/conversation.go:141 +0xe0
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) github.com/twstrike/coyim/gui.(*conversationPane).(github.com/twstrike/coyim/gui.onStartOtrSignal)-fm()
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/home/user/go/src/github.com/twstrike/coyim/gui/conversation.go:227 +0x20
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) reflect.Value.call(0xbbfc40, 0xc82039c670, 0x13, 0x1099f80, 0x4, 0x1cc34c0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/usr/lib/go/src/reflect/value.go:435 +0x120d
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) reflect.Value.Call(0xbbfc40, 0xc82039c670, 0x13, 0x1cc34c0, 0x0, 0x0, 0x0, 0x0, 0x0)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/usr/lib/go/src/reflect/value.go:303 +0xb1
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) github.com/twstrike/coyim/Godeps/_workspace/src/github.com/gotk3/gotk3/glib.goMarshal(0x3048ab0, 0x0, 0x1, 0x3f8a1ae8210, 0x3f8a1ae8190, 0x0)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/home/user/go/src/github.com/twstrike/coyim/Godeps/_workspace/src/github.com/gotk3/gotk3/glib/glib.go:215 +0xa33
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) github.com/twstrike/coyim/Godeps/_workspace/src/github.com/gotk3/gotk3/glib._cgoexpwrap_e2096792664d_goMarshal(0x3048ab0, 0x0, 0x3f800000001, 0x3f8a1ae8210, 0x3f8a1ae8190, 0x0)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011??:0 +0x51
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) github.com/twstrike/coyim/Godeps/_workspace/src/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x1f18200, 0x0, 0x1ed6150, 0x0)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011??:0 +0x41
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) github.com/twstrike/coyim/Godeps/_workspace/src/github.com/gotk3/gotk3/glib.(*Application).Run(0xc8200240a8, 0x1cc34c0, 0x0, 0x0, 0x0)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/home/user/go/src/github.com/twstrike/coyim/Godeps/_workspace/src/github.com/gotk3/gotk3/glib/application.go:199 +0x3d7
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) github.com/twstrike/coyim/gui.(*gtkUI).Loop(0xc8200b6240)
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/home/user/go/src/github.com/twstrike/coyim/gui/ui.go:277 +0x13b
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) main.runClient()
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/home/user/go/src/github.com/twstrike/coyim/gtk.go:24 +0x308
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) main.main()
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] (stderr) #011/home/user/go/src/github.com/twstrike/coyim/main.go:30 +0x3d
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] Child process pid=46 exited from init with status 2
Mar 30 18:10:18 subgraph oz-daemon[31646]: 2016/03/30 18:10:18 [coyim] Shutting down sandbox after child exit.
Mar 30 18:10:19 subgraph oz-daemon[31646]: 2016/03/30 18:10:19 [coyim] (xpra-server) 2016-03-30 18:10:19,229 New unix-domain connection received
Mar 30 18:10:19 subgraph oz-daemon[31646]: 2016/03/30 18:10:19 [coyim] (xpra-server) 2016-03-30 18:10:19,262 Python/GObject Linux client version 0.15.8 connected from 'coyim' as 'user' ('User')
Mar 30 18:10:19 subgraph oz-daemon[31646]: 2016/03/30 18:10:19 [coyim] (xpra-server) 2016-03-30 18:10:19,263 Shutting down in response to request
Mar 30 18:10:20 subgraph oz-daemon[31646]: 2016/03/30 18:10:20 [coyim] (xpra-server) 2016-03-30 18:10:20,264 Disconnecting client '/home/user/.Xoz/coyim/coyim-0': server shutdown
Mar 30 18:10:20 subgraph oz-daemon[31646]: 2016/03/30 18:10:20 [coyim] (xpra-client-stderr) 2016-03-30 18:10:20,267 server requested disconnect: server shutdown
Mar 30 18:10:20 subgraph oz-daemon[31646]: 2016/03/30 18:10:20 [coyim] (xpra-server) 2016-03-30 18:10:20,276 xpra client disconnected.
Mar 30 18:10:20 subgraph oz-daemon[31646]: 2016/03/30 18:10:20 [coyim] (xpra-server) 2016-03-30 18:10:20,277 Disconnecting client '/home/user/.Xoz/coyim/coyim-0': server shutdown
Mar 30 18:10:20 subgraph oz-daemon[31646]: 2016/03/30 18:10:20 [coyim] (xpra-server) 2016-03-30 18:10:20,280 xpra client disconnected.
Mar 30 18:10:20 subgraph oz-daemon[31646]: 2016/03/30 18:10:20 [coyim] (xpra-client-stderr) 2016-03-30 18:10:20,282 Connection lost
```

**Comment by olabini** [comment]
Thanks for the report - this is obviously a problem.
