### ISSUE TITLE
Crash on "Export Private Keys"

### ISSUE THREAD

**Issue by pingberlin** [twstrike/coyim#404]
Coyim crashes when clicking "Export private keys".

Coyim > Help > About tells me I am using version 1.0.

This is the log:

```
(CoyIM:5537): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
SIGTRAP: trace trap
PC=0x7f4e950d5f7b m=0
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xada850, 0xc4201a9270, 0x0)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/cgocall.go:131 +0x110 fp=0xc4201a9220 sp=0xc4201a91e0
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/gtk._Cfunc_gtk_file_chooser_dialog_new_2(0x2a66010, 0x2a7e660, 0x1, 0x2b8bde0, 0xfffffffa, 0x27f8fe0, 0xfffffffb, 0x0)
	??:0 +0x51 fp=0xc4201a9270 sp=0xc4201a9220
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/gtk.FileChooserDialogNewWith2Buttons(0xc4200105a0, 0x13, 0xc4201c8378, 0x1, 0xc4201c2020, 0x7, 0xfffffffffffffffa, 0xc4201c2027, 0x7, 0xfffffffffffffffb, ...)
	/home/user/gopath/src/github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/gtk/gtk.go:3929 +0x1fb fp=0xc4201a92f0 sp=0xc4201a9270
github.com/twstrike/coyim/vendor/github.com/twstrike/gotk3adapter/gtka.(*RealGtk).FileChooserDialogNewWith2Buttons(0x1694ca0, 0xc4200105a0, 0x13, 0x7f4e9653fc90, 0xc43021ac90, 0x1, 0xc4201c2020, 0x7, 0xfffffffffffffffa, 0xc4201c2027, ...)
	/home/user/gopath/src/github.com/twstrike/coyim/vendor/github.com/twstrike/gotk3adapter/gtka/real_gtk.go:78 +0xc2 fp=0xc4201a9368 sp=0xc4201a92f0
github.com/twstrike/coyim/gui.(*gtkUI).exportKeysForDialog(0xc4200e1520, 0xc4201cc420, 0x165aa20, 0xc43021ac90)
	/home/user/gopath/src/github.com/twstrike/coyim/gui/importer.go:307 +0x1be fp=0xc4201a9468 sp=0xc4201a9368
github.com/twstrike/coyim/gui.(*gtkUI).accountDialog.func12()
	/home/user/gopath/src/github.com/twstrike/coyim/gui/account_details.go:355 +0x49 fp=0xc4201a9498 sp=0xc4201a9468
runtime.call32(0xc42019c0c0, 0xc430220380, 0x1696470, 0x0)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/asm_amd64.s:479 +0x4c fp=0xc4201a94c8 sp=0xc4201a9498
reflect.Value.call(0xb56fc0, 0xc430220380, 0x13, 0xc9b4e8, 0x4, 0x1696470, 0x0, 0x0, 0xc4201a9890, 0x2570fa3d, ...)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/reflect/value.go:434 +0x5c8 fp=0xc4201a9818 sp=0xc4201a94c8
reflect.Value.Call(0xb56fc0, 0xc430220380, 0x13, 0x1696470, 0x0, 0x0, 0x0, 0x0, 0x0)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/reflect/value.go:302 +0xa4 fp=0xc4201a9880 sp=0xc4201a9818
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib.goMarshal(0x2b28200, 0x0, 0x1, 0x7ffea4634e90, 0x7ffea4634e10, 0x0)
	/home/user/gopath/src/github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:216 +0x5fe fp=0xc4201a9a58 sp=0xc4201a9880
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_f9ab7d87af52_goMarshal(0x2b28200, 0x0, 0x4024000000000001, 0x7ffea4634e90, 0x7ffea4634e10, 0x0)
	??:0 +0x5b fp=0xc4201a9a98 sp=0xc4201a9a58
runtime.call64(0x0, 0x7ffea4634ba8, 0x7ffea4634c50, 0x30)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/asm_amd64.s:480 +0x4c fp=0xc4201a9ae8 sp=0xc4201a9a98
runtime.cgocallbackg1(0x0)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/cgocall.go:283 +0x19d fp=0xc4201a9b60 sp=0xc4201a9ae8
runtime.cgocallbackg(0x0)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/cgocall.go:170 +0x84 fp=0xc4201a9bc8 sp=0xc4201a9b60
runtime.cgocallback_gofunc(0x451ff8, 0xad3de0, 0xc4201a9c78, 0x1678ba0)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/asm_amd64.s:728 +0x74 fp=0xc4201a9be8 sp=0xc4201a9bc8
runtime.asmcgocall(0xad3de0, 0xc4201a9c78)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/asm_amd64.s:575 +0x42 fp=0xc4201a9bf0 sp=0xc4201a9be8
runtime.cgocall(0xad3de0, 0xc4201a9c78, 0x0)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/cgocall.go:132 +0x128 fp=0xc4201a9c30 sp=0xc4201a9bf0
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0x2621270, 0x0, 0x25e0e30, 0x0)
	??:0 +0x4d fp=0xc4201a9c78 sp=0xc4201a9c30
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc42003c160, 0x1696470, 0x0, 0x0, 0x0)
	/home/user/gopath/src/github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:199 +0x2ca fp=0xc4201a9cf0 sp=0xc4201a9c78
github.com/twstrike/coyim/gui.(*gtkUI).Loop(0xc4200e1520)
	/home/user/gopath/src/github.com/twstrike/coyim/gui/ui.go:298 +0xf8 fp=0xc4201a9d60 sp=0xc4201a9cf0
main.runClient()
	/home/user/gopath/src/github.com/twstrike/coyim/gtk.go:28 +0x1d1 fp=0xc4201a9ea0 sp=0xc4201a9d60
main.main()
	/home/user/gopath/src/github.com/twstrike/coyim/main.go:35 +0xd4 fp=0xc4201a9f38 sp=0xc4201a9ea0
runtime.main()
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/proc.go:183 +0x1f4 fp=0xc4201a9f90 sp=0xc4201a9f38
runtime.goexit()
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4201a9f98 sp=0xc4201a9f90

goroutine 17 [syscall, 3 minutes, locked to thread]:
runtime.goexit()
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 5 [IO wait, 3 minutes]:
net.runtime_pollWait(0x7f4e9653c178, 0x72, 0xc4201a5648)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/runtime/netpoll.go:160 +0x59
net.(*pollDesc).wait(0xc420027100, 0x72, 0xc4201a5788, 0xc42000c210)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/net/fd_poll_runtime.go:73 +0x38
net.(*pollDesc).waitRead(0xc420027100, 0x164d8c0, 0xc42000c210)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/net/fd_poll_runtime.go:78 +0x34
net.(*netFD).readMsg(0xc4200270a0, 0xc4201c29a0, 0x10, 0x10, 0xc4201d7220, 0x1000, 0x1000, 0xffffffffffffffff, 0x0, 0x0, ...)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/net/fd_unix.go:297 +0x243
net.(*UnixConn).readMsg(0xc42003c260, 0xc4201c29a0, 0x10, 0x10, 0xc4201d7220, 0x1000, 0x1000, 0xc4201c2673, 0xc4201c05b0, 0x0, ...)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/net/unixsock_posix.go:111 +0x91
net.(*UnixConn).ReadMsgUnix(0xc42003c260, 0xc4201c29a0, 0x10, 0x10, 0xc4201d7220, 0x1000, 0x1000, 0x0, 0x0, 0xc4201c2892, ...)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/net/unixsock.go:127 +0xaa
github.com/twstrike/coyim/vendor/github.com/godbus/dbus.(*oobReader).Read(0xc4201d7200, 0xc4201c29a0, 0x10, 0x10, 0x1020, 0xc4201d7200, 0x0)
	/home/user/gopath/src/github.com/twstrike/coyim/vendor/github.com/godbus/dbus/transport_unix.go:21 +0x95
io.ReadAtLeast(0x164b1c0, 0xc4201d7200, 0xc4201c29a0, 0x10, 0x10, 0x10, 0xbd5320, 0xb50c01, 0xc4201d7200)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/io/io.go:307 +0xa4
io.ReadFull(0x164b1c0, 0xc4201d7200, 0xc4201c29a0, 0x10, 0x10, 0xa, 0x100000000000000, 0x0)
	/nix/store/jqa9bh404crcxnyxa2lkffag7kw3yxw3-go-1.7.1/share/go/src/io/io.go:325 +0x58
github.com/twstrike/coyim/vendor/github.com/godbus/dbus.(*unixTransport).ReadMessage(0xc42000de40, 0xc4201befe0, 0x14, 0xc9aba4)
	/home/user/gopath/src/github.com/twstrike/coyim/vendor/github.com/godbus/dbus/transport_unix.go:85 +0x15b
github.com/twstrike/coyim/vendor/github.com/godbus/dbus.(*Conn).inWorker(0xc4200f7e60)
	/home/user/gopath/src/github.com/twstrike/coyim/vendor/github.com/godbus/dbus/conn.go:248 +0x4b
created by github.com/twstrike/coyim/vendor/github.com/godbus/dbus.(*Conn).Auth
	/home/user/gopath/src/github.com/twstrike/coyim/vendor/github.com/godbus/dbus/auth.go:118 +0x738

goroutine 6 [chan receive, 3 minutes]:
github.com/twstrike/coyim/vendor/github.com/godbus/dbus.(*Conn).outWorker(0xc4200f7e60)
	/home/user/gopath/src/github.com/twstrike/coyim/vendor/github.com/godbus/dbus/conn.go:385 +0x5d
created by github.com/twstrike/coyim/vendor/github.com/godbus/dbus.(*Conn).Auth
	/home/user/gopath/src/github.com/twstrike/coyim/vendor/github.com/godbus/dbus/auth.go:119 +0x75d

goroutine 7 [chan receive, 3 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).watchCommands(0xc4200e1520)
	/home/user/gopath/src/github.com/twstrike/coyim/gui/commands.go:64 +0xb3
created by github.com/twstrike/coyim/gui.(*gtkUI).onActivate
	/home/user/gopath/src/github.com/twstrike/coyim/gui/ui.go:291 +0x8e

goroutine 8 [chan receive, 3 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).observeAccountEvents(0xc4200e1520)
	/home/user/gopath/src/github.com/twstrike/coyim/gui/account_events.go:48 +0x64
created by github.com/twstrike/coyim/gui.(*gtkUI).onActivate
	/home/user/gopath/src/github.com/twstrike/coyim/gui/ui.go:292 +0xb0

goroutine 36 [chan receive, 3 minutes]:
github.com/twstrike/coyim/session.observe(0xc420022840)
	/home/user/gopath/src/github.com/twstrike/coyim/session/session_observer.go:9 +0x9a
created by github.com/twstrike/coyim/session.Factory
	/home/user/gopath/src/github.com/twstrike/coyim/session/session.go:158 +0x48a

goroutine 37 [chan receive]:
github.com/twstrike/coyim/session.checkReconnect(0xc420022840)
	/home/user/gopath/src/github.com/twstrike/coyim/session/reconnect.go:11 +0x72
created by github.com/twstrike/coyim/session.Factory
	/home/user/gopath/src/github.com/twstrike/coyim/session/session.go:159 +0x4ac

goroutine 38 [chan receive, 3 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).listenToToggleConnectAllAutomatically(0xc4200e1520)
	/home/user/gopath/src/github.com/twstrike/coyim/gui/ui.go:600 +0x4d
created by github.com/twstrike/coyim/gui.(*gtkUI).configLoaded
	/home/user/gopath/src/github.com/twstrike/coyim/gui/ui.go:233 +0x181

goroutine 39 [chan receive, 3 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).listenToSetShowAdvancedSettings(0xc4200e1520)
	/home/user/gopath/src/github.com/twstrike/coyim/gui/ui.go:616 +0x4d
created by github.com/twstrike/coyim/gui.(*gtkUI).configLoaded
	/home/user/gopath/src/github.com/twstrike/coyim/gui/ui.go:234 +0x1a3

goroutine 42 [chan receive, 3 minutes]:
github.com/twstrike/coyim/gui.(*account).runSessionObserver(0xc42011a090)
	/home/user/gopath/src/github.com/twstrike/coyim/gui/account.go:245 +0x6d
created by github.com/twstrike/coyim/gui.(*account).observeConnectionEvents
	/home/user/gopath/src/github.com/twstrike/coyim/gui/account.go:269 +0x1d8

rax    0x0
rbx    0x2
rcx    0x7f4e93d18ded
rdx    0x7f4e93fd6ad8
rdi    0x7f4e93fd6a80
rsi    0x0
rbp    0x4
rsp    0x7ffea4633a50
r8     0x7f4e965d3980
r9     0x1d
r10    0x20
r11    0x0
r12    0x4
r13    0x0
r14    0x7f4e950d5740
r15    0x2
rip    0x7f4e950d5f7b
rflags 0x246
cs     0x33
fs     0x0
gs     0x0
```

**Comment by olabini** [comment]
Hi,

Sorry about that - thanks for the report.

However, we have never released a version 1.0 - which operating system are you using, and how did you install CoyIM?

**Comment by pingberlin** [comment]
Well I guess coyim showing a wrong version in the UI is another bug then.
The version I got is the latest master.
I am using Nixos 16.09 and installed coyim like written in the repositories README.md:

```
export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _ | cut -d '_' -f 1-2)
go get -u -tags "gtk_${GTK_VERSION}" github.com/twstrike/coyim
```

**Comment by pingberlin** [comment]
Are there more dependencies to coyim than listed in the repository Readme.md-file?

**Comment by olabini** [comment]
No, those dependencies should be everything needed - have you seen any problems based on missing dependencies?

**Comment by olabini** [comment]
Which version of GTK and related libraries do you have installed?

**Comment by olabini** [comment]
Would you mind seeing if you have a file named /usr/share/glib-2.0/schemas/gschemas.compiled on your system?

**Comment by olabini** [comment]
Ping

**Comment by olabini** [comment]
no more information about this for 3 months, so I'm closing it for now.
