### ISSUE TITLE
Segfaults at the start

### ISSUE THREAD

**Issue by nogoegst** [twstrike/coyim#414]
This happens on OpenBSD. I've build other stuff with vanilla gotk3 and it works fine. I guess problem with the vendored version of `gotk3` or with `gotk3adapter`. Not sure that this is OpenBSD specific.
```
$ ./coyim
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x298c01380 pc=0xa5e3bb]

runtime stack:
runtime.throw(0xd87d63, 0x2a)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc
runtime.asmcgocall(0xc420045c10, 0xc4200140c0)
        /usr/local/go/src/runtime/asm_amd64.s:594 +0x70
runtime.cgocall(0x7f7ffffdc470, 0x162f040, 0x7f7ffffdc460)
        /usr/local/go/src/runtime/cgocall.go:115 +0xed

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0xa5e3b0, 0xc420045c88, 0xc400000000)
        /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc420045c40 sp=0xc420045c00
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_set_string(0x298c01380, 0x200000000, 0x0)
        ??:0 +0x45 fp=0xc420045c88 sp=0xc420045c40
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc420024150, 0x164ce48, 0x0, 0x0, 0x0)
        /home/unix/gopath/src/github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:197 +0x1f8 fp=0xc420045d00 sp=0xc420045c88
github.com/twstrike/coyim/gui.(*gtkUI).Loop(0xc420148b60)
        /home/unix/gopath/src/github.com/twstrike/coyim/gui/ui.go:298 +0xf8 fp=0xc420045d70 sp=0xc420045d00
main.runClient()
        /home/unix/gopath/src/github.com/twstrike/coyim/gtk.go:28 +0x1d1 fp=0xc420045eb0 sp=0xc420045d70
main.main()
        /home/unix/gopath/src/github.com/twstrike/coyim/main.go:35 +0xd4 fp=0xc420045f48 sp=0xc420045eb0
runtime.main()
        /usr/local/go/src/runtime/proc.go:183 +0x1f4 fp=0xc420045fa0 sp=0xc420045f48
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc420045fa8 sp=0xc420045fa0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1

goroutine 18 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x
```

**Comment by olabini** [comment]
Sorry about this - we haven't tried it on BSD before. We will take a look.

**Comment by nogoegst** [comment]
I've found the cause for this: https://github.com/gotk3/gotk3/pull/157

**Comment by olabini** [comment]
Fantastic, thank you!
I'll keep this issue open until we have merged the fix.

**Comment by olabini** [comment]
Thank you! I've pushed the fix to this in the master repo now.

**Comment by divansantana** [comment]
how to get coy on openbsd?
