### ISSUE TITLE
fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by juniorz** [twstrike/coyim#431]
Coy version: f8e4534
Go version: go version go1.8.3 darwin/amd64
It happened right after the account connected.

```
fatal error: concurrent map iteration and map write

goroutine 1 [running, locked to thread]:
runtime.throw(0x48ade77, 0x26)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:596 +0x95 fp=0xc4202a09b0 sp=0xc4202a0990
runtime.mapiternext(0xc4202a0aa8)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/hashmap.go:737 +0x7ee fp=0xc4202a0a60 sp=0xc4202a09b0
github.com/twstrike/coyim/roster.peersCopy(0xc42015f6b0, 0xc4202a0b60)
	/Users/rjunior/go/src/github.com/twstrike/coyim/roster/group_list.go:40 +0x11d fp=0xc4202a0b18 sp=0xc4202a0a60
github.com/twstrike/coyim/roster.(*List).AddTo(0xc4201b81c0, 0xc4203f6aa0, 0x4895b35, 0x2)
	/Users/rjunior/go/src/github.com/twstrike/coyim/roster/group_list.go:56 +0x46 fp=0xc4202a0c68 sp=0xc4202a0b18
github.com/twstrike/coyim/roster.(*List).Grouped(0xc4201b81c0, 0x4895b35, 0x2, 0x47a0280)
	/Users/rjunior/go/src/github.com/twstrike/coyim/roster/group_list.go:86 +0x174 fp=0xc4202a0cd0 sp=0xc4202a0c68
github.com/twstrike/coyim/gui.(*roster).redrawSeparateAccount(0xc42008b200, 0xc4201da280, 0xc4201b81c0, 0xc4201e0101)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/roster.go:650 +0x107 fp=0xc4202a0f80 sp=0xc4202a0cd0
github.com/twstrike/coyim/gui.(*roster).redrawSeparate(0xc42008b200)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/roster.go:712 +0x16f fp=0xc4202a0fe0 sp=0xc4202a0f80
github.com/twstrike/coyim/gui.(*roster).redraw(0xc42008b200)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/roster.go:730 +0x68 fp=0xc4202a0ff8 sp=0xc4202a0fe0
github.com/twstrike/coyim/gui.(*roster).(github.com/twstrike/coyim/gui.redraw)-fm()
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/roster.go:171 +0x2a fp=0xc4202a1010 sp=0xc4202a0ff8
runtime.call32(0xc42015e4e0, 0xc4204041d0, 0x513d2b0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:514 +0x48 fp=0xc4202a1040 sp=0xc4202a1010
reflect.Value.call(0x474b900, 0xc4204041d0, 0x13, 0x4896387, 0x4, 0x513d2b0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:434 +0x91f fp=0xc4202a1388 sp=0xc4202a1040
reflect.Value.Call(0x474b900, 0xc4204041d0, 0x13, 0x513d2b0, 0x0, 0x0, 0x0, 0x0, 0x4071ab2)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:302 +0xa4 fp=0xc4202a13f0 sp=0xc4202a1388
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib.sourceAttach.func2()
	/Users/rjunior/go/src/github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:311 +0x18c fp=0xc4202a1498 sp=0xc4202a13f0
runtime.call32(0xc42015e4e0, 0xc420015c20, 0x513d2b0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:514 +0x48 fp=0xc4202a14c8 sp=0xc4202a1498
reflect.Value.call(0x474b900, 0xc420015c20, 0x13, 0x4896387, 0x4, 0x513d2b0, 0x0, 0x0, 0xc4202a1888, 0x11c11e26, ...)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:434 +0x91f fp=0xc4202a1810 sp=0xc4202a14c8
reflect.Value.Call(0x474b900, 0xc420015c20, 0x13, 0x513d2b0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/reflect/value.go:302 +0xa4 fp=0xc4202a1878 sp=0xc4202a1810
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib.goMarshal(0x6dbc820, 0x7fff5fbff4c8, 0x0, 0x0, 0x0, 0x0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib/glib.go:216 +0x5ba fp=0xc4202a1a20 sp=0xc4202a1878
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib._cgoexpwrap_e280e468d867_goMarshal(0x6dbc820, 0x7fff5fbff4c8, 0x0, 0x0, 0x0, 0x0)
	github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib/_obj/_cgo_gotypes.go:3566 +0x5b fp=0xc4202a1a60 sp=0xc4202a1a20
runtime.call64(0x0, 0x7fff5fbff348, 0x7fff5fbff3e8, 0x30)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:515 +0x48 fp=0xc4202a1ab0 sp=0xc4202a1a60
runtime.cgocallbackg1(0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/cgocall.go:301 +0x19d fp=0xc4202a1b28 sp=0xc4202a1ab0
runtime.cgocallbackg(0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/cgocall.go:184 +0x84 fp=0xc4202a1b90 sp=0xc4202a1b28
runtime.cgocallback_gofunc(0x400bbda, 0x46c1070, 0xc4202a1c38, 0x511f9a0)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:767 +0x74 fp=0xc4202a1bb0 sp=0xc4202a1b90
runtime.asmcgocall(0x46c1070, 0xc4202a1c38)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:614 +0x42 fp=0xc4202a1bb8 sp=0xc4202a1bb0
runtime.cgocall(0x46c1070, 0xc4202a1c38, 0x48af39f)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/cgocall.go:132 +0xfa fp=0xc4202a1bf8 sp=0xc4202a1bb8
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib._Cfunc_g_application_run(0xe00d0e0, 0x0, 0x6b1d9f0, 0x0)
	github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib/_obj/_cgo_gotypes.go:893 +0x4d fp=0xc4202a1c38 sp=0xc4202a1bf8
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run.func4(0xe00d0e0, 0x0, 0x6b1d9f0, 0x401a058)
	/Users/rjunior/go/src/github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:197 +0xab fp=0xc4202a1c70 sp=0xc4202a1c38
github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib.(*Application).Run(0xc42000e310, 0x513d2b0, 0x0, 0x0, 0x0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/vendor/github.com/gotk3/gotk3/glib/application.go:197 +0x13b fp=0xc4202a1cc0 sp=0xc4202a1c70
github.com/twstrike/coyim/gui.(*gtkUI).Loop(0xc420140ea0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:299 +0xf8 fp=0xc4202a1d30 sp=0xc4202a1cc0
main.runClient()
	/Users/rjunior/go/src/github.com/twstrike/coyim/gtk.go:28 +0x1d1 fp=0xc4202a1e70 sp=0xc4202a1d30
main.main()
	/Users/rjunior/go/src/github.com/twstrike/coyim/main.go:47 +0x66 fp=0xc4202a1f88 sp=0xc4202a1e70
runtime.main()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/proc.go:185 +0x20a fp=0xc4202a1fe0 sp=0xc4202a1f88
runtime.goexit()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4202a1fe8 sp=0xc4202a1fe0

goroutine 17 [syscall, 4 minutes, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/asm_amd64.s:2197 +0x1

goroutine 5 [chan receive, 2 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).watchCommands(0xc420140ea0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/commands.go:62 +0x80
created by github.com/twstrike/coyim/gui.(*gtkUI).onActivate
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:292 +0x93

goroutine 6 [chan receive]:
github.com/twstrike/coyim/gui.(*gtkUI).observeAccountEvents(0xc420140ea0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account_events.go:48 +0x64
created by github.com/twstrike/coyim/gui.(*gtkUI).onActivate
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:293 +0xb5

goroutine 18 [chan receive]:
github.com/twstrike/coyim/session.observe(0xc4201e2000)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session_observer.go:9 +0x8d
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:160 +0x44d

goroutine 19 [chan receive, 2 minutes]:
github.com/twstrike/coyim/session.checkReconnect(0xc4201e2000)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/reconnect.go:10 +0x72
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:161 +0x46f

goroutine 20 [chan receive, 4 minutes]:
github.com/twstrike/coyim/session.observe(0xc4201e2160)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session_observer.go:9 +0x8d
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:160 +0x44d

goroutine 21 [chan receive, 2 minutes]:
github.com/twstrike/coyim/session.checkReconnect(0xc4201e2160)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/reconnect.go:10 +0x72
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:161 +0x46f

goroutine 22 [chan receive, 4 minutes]:
github.com/twstrike/coyim/session.observe(0xc4201e22c0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session_observer.go:9 +0x8d
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:160 +0x44d

goroutine 23 [chan receive]:
github.com/twstrike/coyim/session.checkReconnect(0xc4201e22c0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/reconnect.go:10 +0x72
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:161 +0x46f

goroutine 24 [chan receive, 4 minutes]:
github.com/twstrike/coyim/session.observe(0xc4201e2420)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session_observer.go:9 +0x8d
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:160 +0x44d

goroutine 25 [chan receive]:
github.com/twstrike/coyim/session.checkReconnect(0xc4201e2420)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/reconnect.go:10 +0x72
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:161 +0x46f

goroutine 26 [chan receive, 4 minutes]:
github.com/twstrike/coyim/session.observe(0xc4201e2580)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session_observer.go:9 +0x8d
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:160 +0x44d

goroutine 27 [chan receive, 2 minutes]:
github.com/twstrike/coyim/session.checkReconnect(0xc4201e2580)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/reconnect.go:10 +0x72
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:161 +0x46f

goroutine 28 [chan receive, 4 minutes]:
github.com/twstrike/coyim/session.observe(0xc4201e26e0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session_observer.go:9 +0x8d
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:160 +0x44d

goroutine 29 [chan receive, 2 minutes]:
github.com/twstrike/coyim/session.checkReconnect(0xc4201e26e0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/reconnect.go:10 +0x72
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:161 +0x46f

goroutine 30 [chan receive, 2 minutes]:
github.com/twstrike/coyim/session.observe(0xc4201e2840)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session_observer.go:9 +0x8d
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:160 +0x44d

goroutine 31 [chan receive]:
github.com/twstrike/coyim/session.checkReconnect(0xc4201e2840)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/reconnect.go:10 +0x72
created by github.com/twstrike/coyim/session.Factory
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:161 +0x46f

goroutine 32 [chan receive, 4 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).listenToToggleConnectAllAutomatically(0xc420140ea0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:605 +0x4d
created by github.com/twstrike/coyim/gui.(*gtkUI).configLoaded
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:234 +0x183

goroutine 33 [chan receive, 4 minutes]:
github.com/twstrike/coyim/gui.(*gtkUI).listenToSetShowAdvancedSettings(0xc420140ea0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:621 +0x4d
created by github.com/twstrike/coyim/gui.(*gtkUI).configLoaded
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/ui.go:235 +0x1a5

goroutine 220 [chan receive]:
github.com/twstrike/coyim/gui.(*account).runSessionObserver(0xc4201dac80)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:273 +0x60
created by github.com/twstrike/coyim/gui.(*account).observeConnectionEvents
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:297 +0x1d1

goroutine 315 [runnable]:
github.com/twstrike/coyim/session.(*session).receiveStanza(0xc4201e2000, 0xc4202081e0, 0xc4201e2001)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:328 +0x84
github.com/twstrike/coyim/session.(*session).watchStanzas(0xc4201e2000)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:355 +0xa9
created by github.com/twstrike/coyim/session.(*session).Connect
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:938 +0x23f

goroutine 217 [chan receive]:
github.com/twstrike/coyim/gui.(*account).runSessionObserver(0xc4201da500)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:273 +0x60
created by github.com/twstrike/coyim/gui.(*account).observeConnectionEvents
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:297 +0x1d1

goroutine 314 [chan receive]:
github.com/twstrike/coyim/session.(*session).watchTimeout(0xc4201e2000)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:764 +0x9f
created by github.com/twstrike/coyim/session.(*session).Connect
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:937 +0x21a

goroutine 219 [chan receive]:
github.com/twstrike/coyim/gui.(*account).runSessionObserver(0xc4201daa00)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:273 +0x60
created by github.com/twstrike/coyim/gui.(*account).observeConnectionEvents
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:297 +0x1d1

goroutine 290 [select]:
net/http.(*persistConn).writeLoop(0xc4204226c0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1704 +0x43a
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1118 +0xa5a

goroutine 307 [chan receive]:
github.com/twstrike/coyim/xmpp.(*conn).watchPings(0xc420097b00)
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/ping.go:61 +0xd3
created by github.com/twstrike/coyim/xmpp.(*dialer).setupStream
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/dialer.go:133 +0x270

goroutine 99 [sleep, 2 minutes]:
time.Sleep(0x29e8d60800)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/time.go:59 +0xf9
github.com/twstrike/coyim/session.(*session).watchRoster(0xc4201e2840)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:800 +0x47
created by github.com/twstrike/coyim/session.(*session).Connect
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:935 +0x1d0

goroutine 218 [chan receive]:
github.com/twstrike/coyim/gui.(*account).runSessionObserver(0xc4201da780)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:273 +0x60
created by github.com/twstrike/coyim/gui.(*account).observeConnectionEvents
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:297 +0x1d1

goroutine 316 [IO wait]:
net.runtime_pollWait(0x1418ee68, 0x72, 0x18)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc420168228, 0x72, 0x50d7600, 0x50d2410)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc420168228, 0xc42047d3f6, 0xc0a)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc4201681c0, 0xc42047d3f6, 0xc0a, 0xc0a, 0x0, 0x50d7600, 0x50d2410)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc4201be000, 0xc42047d3f6, 0xc0a, 0xc0a, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/net.go:181 +0x70
crypto/tls.(*block).readFromUntil(0xc4203aa150, 0x6a8b388, 0xc4201be000, 0x558, 0xc4201be000, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/crypto/tls/conn.go:488 +0x98
crypto/tls.(*Conn).readRecord(0xc420522000, 0x48f7f17, 0xc420522120, 0xc420188001)
	/usr/local/Cellar/go/1.8.3/libexec/src/crypto/tls/conn.go:635 +0x1fa
crypto/tls.(*Conn).Read(0xc420522000, 0xc42047c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/crypto/tls/conn.go:1134 +0x11d
io.(*teeReader).Read(0xc4203c4220, 0xc42047c000, 0x1000, 0x1000, 0x5, 0xc4204321e0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/io/io.go:523 +0x55
bufio.(*Reader).fill(0xc420208120)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).ReadByte(0xc420208120, 0xc4204321e0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:239 +0x5b
encoding/xml.(*Decoder).getc(0xc4202ac000, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/encoding/xml/xml.go:871 +0x99
encoding/xml.(*Decoder).rawToken(0xc4202ac000, 0x0, 0x0, 0xc42041a200, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/encoding/xml/xml.go:517 +0x69
encoding/xml.(*Decoder).Token(0xc4202ac000, 0xc4203f4090, 0x21, 0xc4204321e0, 0x13)
	/usr/local/Cellar/go/1.8.3/libexec/src/encoding/xml/xml.go:249 +0x1539
github.com/twstrike/coyim/xmpp.nextElement(0xc4202ac000, 0xc4202ac000, 0xc42038e570, 0xd, 0xc420414008)
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/xml.go:46 +0x5e
github.com/twstrike/coyim/xmpp.next(0x50e38e0, 0xc420097b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/xml.go:90 +0xba
github.com/twstrike/coyim/xmpp.(*conn).Next(0xc420097b00, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/connection.go:194 +0x71
github.com/twstrike/coyim/xmpp.(*conn).ReadStanzas(0xc420097b00, 0xc4202081e0, 0x0, 0x0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/connection.go:285 +0xbc
github.com/twstrike/coyim/session.(*session).readStanzasAndAlertOnErrors(0xc4201e2000, 0xc4202081e0)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:360 +0x44
created by github.com/twstrike/coyim/session.(*session).watchStanzas
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:354 +0x91

goroutine 124 [chan receive, 4 minutes]:
github.com/twstrike/coyim/session.(*session).listenToDelayedMessageDelivery(0xc4201e2840, 0xc42027ec00, 0xc420426a60, 0x18)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:506 +0x45
created by github.com/twstrike/coyim/session.(*session).NewConversation
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:548 +0x358

goroutine 123 [chan receive, 4 minutes]:
github.com/twstrike/coyim/session.(*session).listenToNotifications(0xc4201e2840, 0xc42027ea80, 0xc420426a60, 0x18)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:496 +0x57
created by github.com/twstrike/coyim/session.(*session).NewConversation
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:545 +0x2d6

goroutine 312 [chan receive]:
github.com/twstrike/coyim/session.(*session).requestRoster(0xc4201e2000, 0xc4201e2000)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:859 +0x161
github.com/twstrike/coyim/session.(*session).watchRoster(0xc4201e2000)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:799 +0x2b
created by github.com/twstrike/coyim/session.(*session).Connect
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/session.go:935 +0x1d0

goroutine 306 [chan receive]:
github.com/twstrike/coyim/xmpp.(*conn).watchKeepAlive(0xc420097b00, 0x50deda0, 0xc4201be000)
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/keepalive.go:26 +0x169
created by github.com/twstrike/coyim/xmpp.(*dialer).setupStream
	/Users/rjunior/go/src/github.com/twstrike/coyim/xmpp/dialer.go:132 +0x24e

goroutine 216 [chan receive]:
github.com/twstrike/coyim/gui.(*account).runSessionObserver(0xc4201da280)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:273 +0x60
created by github.com/twstrike/coyim/gui.(*account).observeConnectionEvents
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:297 +0x1d1

goroutine 221 [chan receive]:
github.com/twstrike/coyim/gui.(*account).runSessionObserver(0xc4201daf00)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:273 +0x60
created by github.com/twstrike/coyim/gui.(*account).observeConnectionEvents
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:297 +0x1d1

goroutine 222 [chan receive]:
github.com/twstrike/coyim/gui.(*account).runSessionObserver(0xc4201db180)
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:273 +0x60
created by github.com/twstrike/coyim/gui.(*account).observeConnectionEvents
	/Users/rjunior/go/src/github.com/twstrike/coyim/gui/account.go:297 +0x1d1

goroutine 273 [IO wait]:
net.runtime_pollWait(0x1418ece8, 0x72, 0x1e)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/netpoll.go:164 +0x59
net.(*pollDesc).wait(0xc4201680d8, 0x72, 0x50d7600, 0x50d2410)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:75 +0x38
net.(*pollDesc).waitRead(0xc4201680d8, 0xc4200eb000, 0x1000)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_poll_runtime.go:80 +0x34
net.(*netFD).Read(0xc420168070, 0xc4200eb000, 0x1000, 0x1000, 0x0, 0x50d7600, 0x50d2410)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/fd_unix.go:250 +0x1b7
net.(*conn).Read(0xc42000f8c8, 0xc4200eb000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/net.go:181 +0x70
crypto/tls.(*block).readFromUntil(0xc4201dc000, 0x6a8b388, 0xc42000f8c8, 0x5, 0xc42000f8c8, 0xc42051d870)
	/usr/local/Cellar/go/1.8.3/libexec/src/crypto/tls/conn.go:488 +0x98
crypto/tls.(*Conn).readRecord(0xc420346a80, 0x48f7f17, 0xc420346ba0, 0x405a8b0)
	/usr/local/Cellar/go/1.8.3/libexec/src/crypto/tls/conn.go:590 +0xc4
crypto/tls.(*Conn).Read(0xc420346a80, 0xc420540000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/crypto/tls/conn.go:1134 +0x11d
net/http.(*persistConn).Read(0xc4204226c0, 0xc420540000, 0x1000, 0x1000, 0x5, 0x4058cd0, 0xc42027e480)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1316 +0x14b
bufio.(*Reader).fill(0xc4201de7e0)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:97 +0x117
bufio.(*Reader).Peek(0xc4201de7e0, 0x1, 0xc42051dbe5, 0x1, 0x0, 0xc4201de840, 0x0)
	/usr/local/Cellar/go/1.8.3/libexec/src/bufio/bufio.go:129 +0x67
net/http.(*persistConn).readLoop(0xc4204226c0)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1474 +0x196
created by net/http.(*Transport).dialConn
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/transport.go:1117 +0xa35

goroutine 94 [runnable]:
github.com/twstrike/coyim/session.(*session).publishEventTo(0xc4201e2000, 0xc4201ea000, 0x47cc2a0, 0xc4204c6220)
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:32
created by github.com/twstrike/coyim/session.(*session).publishEvent
	/Users/rjunior/go/src/github.com/twstrike/coyim/session/events.go:63 +0xd0
```

**Comment by juniorz** [comment]
More information: https://golang.org/doc/go1.8#mapiter

**Comment by olabini** [comment]
nice. I'll take a look

**Comment by olabini** [comment]
I've fixed all the races detected - but the original race is still there, so leaving this bug open until I get that sorted out.

**Comment by juniorz** [comment]
Great. I've changed the `test` task to detect these problems.

**Comment by juniorz** [comment]
I'm thinking again now, maybe this error happened before f8e4534. I took the version from `git log` and not from the app. So if you can't find the cause, it may have been fixed already.

**Comment by olabini** [comment]
Sadly the stack traces line up with the changes I made, so I must have misunderstood the reasons for the race there. I'll see if I can find it.

**Comment by olabini** [comment]
I think I fixed it for real - we already had a lock for that structure, but weren't using it in that specific place. I can't reproduce this problem, but I'm fairly confident this will fix it.
